name: Hello World

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World
      run: echo "Hello World"